# Generated by Django 4.2.6 on 2024-01-04 17:30

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customeruser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=12, prefix='', primary_key=True, serialize=False),
        ),
    ]
