# Generated by Django 4.2.6 on 2023-12-24 10:08

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='digital',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=10, max_length=12, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
