# Generated by Django 4.2.6 on 2024-01-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_author_name_alter_author_slug_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
        migrations.AlterField(
            model_name='booklanguage',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booktype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
